apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
    creationTimestamp: "2021-11-01T07:45:12Z"
    generation: 3
    labels:
      app: backend
    name: backend
    namespace: url-shortener
    resourceVersion: "11267657"
    selfLink: /apis/apps/v1/namespaces/url-shortener/deployments/backend
    uid: 09eb084d-0a82-4f78-aea0-2e029eac971a
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: backend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: backend
      spec:
        containers:
        - env:
          - name: DB_HOST
            value: mariadb
          - name: DB_PASS
            value: urlshortener
          image: dungviettran89/url-shortener-backend-java-spring:latest
          imagePullPolicy: Always
          name: url-shortener-backend-java-spring
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2021-11-01T07:45:12Z"
      lastUpdateTime: "2021-11-01T07:45:36Z"
      message: ReplicaSet "backend-668d7fb5db" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2021-11-01T07:46:31Z"
      lastUpdateTime: "2021-11-01T07:46:31Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      field.cattle.io/ipAddresses: "null"
      field.cattle.io/targetDnsRecordIds: "null"
      field.cattle.io/targetWorkloadIds: "null"
    creationTimestamp: "2021-11-01T07:47:07Z"
    labels:
      app: backend
    name: backend
    namespace: url-shortener
    resourceVersion: "11268181"
    selfLink: /api/v1/namespaces/url-shortener/services/backend
    uid: 25f6aacd-8da8-4266-b631-c5205f929f3f
  spec:
    clusterIP: 10.43.46.96
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: backend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
