spring:
  datasource:
    url: "jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    username: "${DB_USER:urlshortener}"
    password: "${DB_PASS:urlshortener}"
  jpa:
    hibernate:
      ddl-auto: update